# Generated by Django 5.2.1 on 2025-05-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
    ]
